general {
  disable_loading_bar = true
  hide_cursor = true
}

background {
  monitor =
  color = rgba(10,10,10,1.0)
}

input-field {
  monitor =
  size = 300, 50
  outline_thickness = 2
  dots_size = 0.25
  dots_spacing = 0.35
  dots_center = true
  position = 0, -100
  halign = center
  valign = center
}
